package scis.ui;

import scis.ui.customers.CreateCustomerPanel;
import scis.ui.customers.ShowCustomersPanel;
import scis.ui.products.CreateProductPanel;
import scis.ui.products.ShowProductsPanel;
import scis.ui.sales.CreateSalePanel;
import scis.ui.sales.ShowSalesPanel;
import scis.utility.AppUtils;


public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        miNewSaleActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnProducts = new javax.swing.JButton();
        btnCustomers = new javax.swing.JButton();
        btnSale = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnExit = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        pnlContainer = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        miExit = new javax.swing.JMenuItem();
        productMenu = new javax.swing.JMenu();
        miNewProduct = new javax.swing.JMenuItem();
        miProductList = new javax.swing.JMenuItem();
        customerMenu = new javax.swing.JMenu();
        miNewCust = new javax.swing.JMenuItem();
        miCustomerList = new javax.swing.JMenuItem();
        saleMenu = new javax.swing.JMenu();
        miNewSale = new javax.swing.JMenuItem();
        miSaleList = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnProducts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/products.png"))); // NOI18N
        btnProducts.setText("Products");
        btnProducts.setFocusable(false);
        btnProducts.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProducts.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductsActionPerformed(evt);
            }
        });
        jToolBar1.add(btnProducts);

        btnCustomers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer.png"))); // NOI18N
        btnCustomers.setText("Customers");
        btnCustomers.setFocusable(false);
        btnCustomers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCustomers.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomersActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCustomers);

        btnSale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cash-register.png"))); // NOI18N
        btnSale.setText("Sale");
        btnSale.setFocusable(false);
        btnSale.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSale.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaleActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSale);

        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jToolBar1.add(jSeparator1);

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logout.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExit);
        jToolBar1.add(filler1);

        pnlContainer.setBorder(null);
        pnlContainer.setLayout(new java.awt.CardLayout());

        fileMenu.setText("File");

        miExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        fileMenu.add(miExit);

        jMenuBar1.add(fileMenu);

        productMenu.setText("Products");

        miNewProduct.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        miNewProduct.setText("New Product");
        miNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNewProductActionPerformed(evt);
            }
        });
        productMenu.add(miNewProduct);

        miProductList.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        miProductList.setText("Product List");
        miProductList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProductListActionPerformed(evt);
            }
        });
        productMenu.add(miProductList);

        jMenuBar1.add(productMenu);

        customerMenu.setText("Customer");

        miNewCust.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        miNewCust.setText("New Customer");
        miNewCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNewCustActionPerformed(evt);
            }
        });
        customerMenu.add(miNewCust);

        miCustomerList.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        miCustomerList.setText("Customer List");
        miCustomerList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCustomerListActionPerformed(evt);
            }
        });
        customerMenu.add(miCustomerList);

        jMenuBar1.add(customerMenu);

        saleMenu.setText("Sale");

        miNewSale.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        miNewSale.setText("New Sale");
        miNewSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNewSaleActionPerformed(evt);
            }
        });
        saleMenu.add(miNewSale);

        miSaleList.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        miSaleList.setText("Sale List");
        miSaleList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSaleListActionPerformed(evt);
            }
        });
        saleMenu.add(miSaleList);

        jMenuBar1.add(saleMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        miExitActionPerformed(evt);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaleActionPerformed
        miSaleListActionPerformed(evt);
    }//GEN-LAST:event_btnSaleActionPerformed

    private void btnCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomersActionPerformed
        miCustomerListActionPerformed(evt);
    }//GEN-LAST:event_btnCustomersActionPerformed

    private void btnProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductsActionPerformed
        miProductListActionPerformed(evt);
    }//GEN-LAST:event_btnProductsActionPerformed

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        boolean answer = AppUtils.confirmDialog(this, "Are you sure you want to exit?");
        if(answer) System.exit(0);
    }//GEN-LAST:event_miExitActionPerformed

    private void miNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNewProductActionPerformed
        CreateProductPanel cpp = new CreateProductPanel();
        AppUtils.bootDialog(this, cpp, "New Product", e ->{

        });
    }//GEN-LAST:event_miNewProductActionPerformed

    private void miProductListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProductListActionPerformed
        ShowProductsPanel spp = new ShowProductsPanel();
        AppUtils.replacePanel(this, pnlContainer,spp);
    }//GEN-LAST:event_miProductListActionPerformed

    private void miNewCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNewCustActionPerformed
        CreateCustomerPanel ccp = new CreateCustomerPanel();
        AppUtils.bootDialog(this, ccp, "New Customer", e ->{

        });
    }//GEN-LAST:event_miNewCustActionPerformed

    private void miCustomerListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCustomerListActionPerformed
        ShowCustomersPanel scp = new ShowCustomersPanel();
        AppUtils.replacePanel(this, pnlContainer,scp);
    }//GEN-LAST:event_miCustomerListActionPerformed

    private void miNewSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNewSaleActionPerformed
        CreateSalePanel csp = new CreateSalePanel();
        AppUtils.replacePanel(this, pnlContainer,csp);
    }//GEN-LAST:event_miNewSaleActionPerformed

    private void miSaleListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSaleListActionPerformed
        ShowSalesPanel ssp = new ShowSalesPanel();
        AppUtils.replacePanel(this, pnlContainer,ssp);
    }//GEN-LAST:event_miSaleListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame mf = new MainFrame();
                mf.setLocationRelativeTo(null);
                mf.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomers;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnProducts;
    private javax.swing.JButton btnSale;
    private javax.swing.JMenu customerMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem miCustomerList;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miNewCust;
    private javax.swing.JMenuItem miNewProduct;
    private javax.swing.JMenuItem miNewSale;
    private javax.swing.JMenuItem miProductList;
    private javax.swing.JMenuItem miSaleList;
    private javax.swing.JPanel pnlContainer;
    private javax.swing.JMenu productMenu;
    private javax.swing.JMenu saleMenu;
    // End of variables declaration//GEN-END:variables
}
