package scis.ui.sales;

import scis.model.Customers;
import scis.model.Products;
import scis.ui.CreateProcessor;
import scis.utility.AppUtils;
import scis.Data;

import javax.swing.*;
import java.util.*;


public class CreateSalePanel extends javax.swing.JPanel implements CreateProcessor {

    private String saleID;
    private boolean isSaleCreated;

    /**
     * Creates new form CreateSalesPanel
     */
    public CreateSalePanel() {
        initComponents();
        setFreshData();
    }

    private String generateRandomSaleID() {
        return AppUtils.generateRandomString();
    }

    private void setFreshData() {
        String saleID = generateRandomSaleID();
        lblInvoiceIDNum.setText(saleID);

        String getPresentDate = AppUtils.formattedDate(new Date());
        txtDate.setText(getPresentDate);


        List<Customers> customers = getCustomers();
        DefaultComboBoxModel<Customers> customerComboModel = AppUtils.getModel(customers);
        cmbCustumers.setModel(customerComboModel);

        List<Products> products = getProducts();
        System.out.println(products);
    }

    private List<Products> getProducts() {
        AppUtils.openDB();
        List<Products> products = Data.getProducts();
        AppUtils.closeDB(this);
        return products;
    }

    private List<Customers> getCustomers() {
        AppUtils.openDB();
        List<Customers> customers = Data.getCustomers();
        AppUtils.closeDB(this);
        return customers;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddNewSaleDetails = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSaleDetails = new javax.swing.JTable();
        cmbCustumers = new javax.swing.JComboBox<>();
        lblCustomers = new javax.swing.JLabel();
        btnSaveInvoice = new javax.swing.JButton();
        lblDate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        lblTotalAmount = new javax.swing.JLabel();
        lblInvoiceID = new javax.swing.JLabel();
        lblInvoiceIDNum = new javax.swing.JLabel();

        btnAddNewSaleDetails.setText("Add New");

        tblSaleDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Quantity", "Price", "Delete"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSaleDetails);

        lblCustomers.setText("Customer");

        btnSaveInvoice.setText("Save Invoice");
        btnSaveInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveInvoiceActionPerformed(evt);
            }
        });

        lblDate.setText("Date");

        txtDate.setEnabled(false);

        lblTotal.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblTotal.setText("Total :");

        lblTotalAmount.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblTotalAmount.setForeground(new java.awt.Color(175, 55, 55));

        lblInvoiceID.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblInvoiceID.setText("Invoice ID:");

        lblInvoiceIDNum.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSaveInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInvoiceID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInvoiceIDNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddNewSaleDetails)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCustomers)
                                .addGap(9, 9, 9)
                                .addComponent(cmbCustumers, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblInvoiceIDNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInvoiceID, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCustumers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCustomers)
                    .addComponent(lblDate)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddNewSaleDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTotalAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSaveInvoice)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveInvoiceActionPerformed
        //We don't need to get the date because in Data.java, it creates it automatically by itself while saving a new Sale

        List<String> errors = validateSaleDetails();
        Customers customer = (Customers)cmbCustumers.getSelectedItem();

    }//GEN-LAST:event_btnSaveInvoiceActionPerformed


    private List<String> validateSaleDetails() {
        return null;
    }


    @Override
    public void success() {
        isSaleCreated = true;
    }

    @Override
    public void resetEverything() {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewSaleDetails;
    private javax.swing.JButton btnSaveInvoice;
    private javax.swing.JComboBox<Customers> cmbCustumers;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCustomers;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblInvoiceID;
    private javax.swing.JLabel lblInvoiceIDNum;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalAmount;
    private javax.swing.JTable tblSaleDetails;
    private javax.swing.JTextField txtDate;
    // End of variables declaration//GEN-END:variables
}
